pipeline {
    environment { 
        PING_IDENTITY_DEVOPS_USER = 'blah'
        PING_IDENTITY_DEVOPS_KEY = 'blah'
    }

    agent {
        kubernetes {
            yamlFile 'DataGovernance/KubernetesPod.yaml'
        }
    }

    stages {
        stage('Run JMeter Test') {
            steps {
                container('jmeter') {
                    git branch: 'main', url: 'https://github.com/gtom-ping/jmx-files'
                    sh '${JMETER_BIN}/jmeter -n -t SanityCheck8443.jmx -l results.csv'
                    perfReport errorFailedThreshold: 0, sourceDataFiles: 'results.csv'
                }
            }
        }
    }
}