pipeline {
    agent {
        kubernetes {
            yamlFile 'DG-pod.yaml'
        }
    }

    stages {
        stage('Run JMeter Test') {
            container('jmeter') {
                steps {
                    git branch: 'main', url: 'https://github.com/gtom-ping/jmx-files'
                    sh '${JMETER_BIN}/jmeter -n -t SanityCheck8443.jmx -l results.csv'
                    perfReport errorFailedThreshold: 0, sourceDataFiles: 'results.csv'
                }
            }
        }
    }
}