apiVersion: v1
kind: Pod
metadata:
  name: DG Performance Pod
  labels:
    name: dg-performance-pod
spec:
  containers:
  - name: datagovernance
    image: 574076504146.dkr.ecr.us-west-2.amazonaws.com/snapshot-builds/pingdatagovernance:latest
    # image: '574076504146.dkr.ecr.us-west-2.amazonaws.com/snapshot-builds/pingdatagovernance:8.3.0.0-SNAPSHOT-alpine-az11-20210112'
    # image: pingidentity/pingdatagovernance:latest
    envs: 
      - name: SERVER_PROFILE_URL
        value: "https://github.com/pingidentity/pingidentity-server-profiles.git"
      - name: SERVER_PROFILE_PATH
        value: "perf-testing/pingdatagovernance"
      - name: PING_IDENTITY_ACCEPT_EULA
        value: "YES"
      - name: SERVER_PROFILE_BRANCH
        value: "dg-root-pw"
    envFrom:
      - secretRef:
          name: devops-secret
          optional: true
    alwaysPullImage: true
    ports:
      - containerPort: 80
      - containerPort: 443
      - containerPort: 636

  - name: upstream-api
    image: samirgandhi/dg-qa-upstream-api
    ports:
      - containerPort: 3000

  - name: dataconsole
    image: 'pingidentity/pingdataconsole:edge'
    ports:
      - containerPort: 8443 
